#!/bin/bash

echo "📱 Deploy to Physical iPhone Guide"
echo "=================================="
echo ""
echo "To deploy to your connected iPhone, you need to:"
echo ""
echo "1. Open Xcode:"
echo "   open DatacapMobileTokenDemo/DatacapMobileTokenDemo.xcodeproj"
echo ""
echo "2. Configure Code Signing:"
echo "   - Select the project in the navigator"
echo "   - Select 'DatacapMobileTokenDemo' target"
echo "   - Go to 'Signing & Capabilities' tab"
echo "   - Check 'Automatically manage signing'"
echo "   - Select your Team (or add your Apple ID)"
echo ""
echo "3. Select Your Device:"
echo "   - In the toolbar at the top, click the device selector"
echo "   - Choose 'iPhone (310)' from the list"
echo ""
echo "4. Build and Run:"
echo "   - Press ⌘+R or click the Play button"
echo "   - If prompted, unlock your iPhone and trust the developer"
echo ""
echo "5. Trust the Developer (first time only):"
echo "   - On your iPhone: Settings → General → VPN & Device Management"
echo "   - Tap your developer profile"
echo "   - Tap 'Trust [Your Name]'"
echo ""
echo "Press Enter to open Xcode now..."
read

open DatacapMobileTokenDemo/DatacapMobileTokenDemo.xcodeproj