#!/bin/bash

# Verify captured screenshots

echo "📸 Screenshot Verification"
echo "========================="
echo ""

SCREENSHOT_DIR="AppStoreAssets/Screenshots/Interactive_20250617_100330"

echo "Your screenshots are ready in:"
echo "$SCREENSHOT_DIR"
echo ""
echo "Expected content for each screenshot:"
echo ""
echo "1️⃣  1_Home.png"
echo "   - Datacap logo"
echo "   - 'Get Secure Token' button" 
echo "   - Feature cards"
echo "   - DEMO MODE indicator"
echo ""
echo "2️⃣  2_CardEntry.png"
echo "   - Card input form"
echo "   - Partial card number (4111 1111)"
echo "   - Keyboard visible"
echo "   - Visa card icon"
echo ""
echo "3️⃣  3_Success.png"
echo "   - Green checkmark"
echo "   - Token displayed"
echo "   - Masked card number"
echo "   - OK button"
echo ""
echo "4️⃣  4_Settings.png"
echo "   - API Configuration title"
echo "   - Mode selector (Demo/Cert/Prod)"
echo "   - API key field"
echo "   - Save button"
echo ""
echo "5️⃣  5_Help.png"
echo "   - 'How It Works' title"
echo "   - Operation modes cards"
echo "   - Key Features section"
echo "   - Close (X) button"
echo ""
echo "6️⃣  6_Transaction.png"
echo "   - Transaction amount ($25.00)"
echo "   - Number pad"
echo "   - Saved token card (if any)"
echo "   - Process Transaction button"
echo ""

# Open Finder to view screenshots
open "$SCREENSHOT_DIR"

echo "✅ Screenshots opened in Finder for review"
echo ""
echo "If any screenshots need to be retaken:"
echo "1. Delete the incorrect screenshot"
echo "2. Use: xcrun simctl io CE797196-6656-4CC7-9886-9D3C489742AE screenshot [filename]"
echo "3. Or run ./capture-screenshots-interactive.sh again"